# Generated by Django 2.2.12 on 2020-04-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='number_of_orders',
            field=models.IntegerField(default=0),
        ),
    ]
