# Generated by Django 2.2.12 on 2020-04-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_number_of_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='number_of_orders',
            new_name='orders',
        ),
    ]
