# Generated by Django 2.2.12 on 2020-04-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200423_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='canceled_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
